---
title: "Julia Pollak Published Abstracts"
output:
  html_document: default
  html_notebook: default
  pdf_document: default
  word_document: default
---

Pollak J., Rai K.G., Paddison P.J., Rostomily R.C., Ramirez J.-M. Transcriptional profiling of glioblastoma stem-like cells reveals enrichment of ion channels with functional implications for malignancy. American Association for Cancer Research, April 2016

Anderson, T.M., Garcia III, A.J., Bloom, J.C., Baertsch, N.A., Pollak, J., Ramirez, J.-M. Postinspiratory Complex: A Third Excitatory Respiratory Oscillator. Experimental Biology, April 2016

Pollak J., Rai K.G., Paddison P.J., Rostomily R.C., Ramirez J.-M. RNA-seq expression profiling of ion channels in glioblastoma stem cells. Society for Neuroscience, October 2015

Anderson, T.M., Garcia III, A.J., Bloom, J.C., Baertsch, N.A., Pollak, J., Ramirez, J.-M. Postinspiration: Generated by a third excitatory rhythmogenic network. Society for Neuroscience, October 2015

Anderson, T.M., Garcia III, A.J., Bloom, J.C., Baertsch, N.A., Pollak, J., Ramirez, J.-M. Coupled Oscillators Underlying Inspiration and Post-inspiration. Experimental Biology, March 2015

Ueki, Y., Pollak, J., Wilken, M.S., Cox, K.E., Taylor, R.J., Reh, T.A. Regeneration of the mammalian retina by Müller glial stimulation. Wellcome Trust Conference, Regenerative Medicine: From Biology to Therapy, 2013, Platform presentation

Pollak J., Wilken M.S., Ueki Y., Cox K., Taylor R.A, Reh T.A. Ascl1 reprograms Müller glia into functional retinal neurons. The Association for Research in Vision and Ophthalmology, May 2013

Pollak J., Wilken M.S., Ueki Y., Taylor R.A, Reh T.A. Ascl1 reprograms Müller glia into neurogenic retinal progenitors. Northwest Developmental Biology Conference, March 2013, Platform presentation 

Pollak J., Wilken M.S., Ueki Y., Taylor R.A, Reh T.A. Ascl1 reprograms Müller glia to a neurogenic fate in the mouse retina. Northwest Developmental Biology Conference, March 2012 

Caras M.L., Pollak J., Fung S., Mehravari A., Watari H. Sustainability of outreach programs over time: A look back through the first five years. Society for Neuroscience, November 2011

Pollak J., Wilken M.S., Ueki Y., Taylor R.A, Reh T.A. Reprogramming Müller glia into retinal neurons with Ascl1. Society for Neuroscience, November 2011

Han J., Pollak J., Yang T., Taravosh-Lahn K., Doyle K., Cekanaviciute E., Han A., Goodman J., Jones B., Jing D., Longo F., Buckwalter M.  A small molecule TrkB ligand promotes recovery when started 3 days after stroke, Neurocritical Care Society, September 2011

Pollak J. and Reh T.A. Ascl1 reprograms Müller glia to generate retinal neurons. Northwest Developmental Biology Conference, March 2011

Han J., Pollak J., Yang T., Taravosh-Lahn K., Doyle K., Cekanaviciute E., Han A., Goodman J., Jones B., Jing D., Longo F., Buckwalter M. A small molecule brain-derived neurotrophic factor mimetic, administered beginning three days after stroke, improves functional recovery. Intl. Stroke Conference, February 2011

Nutt S.E., Pollak J., Chang E.A., Suhr S., Cibelli J., Horner P.J. Induced pluripotent stem cell-derived astrocytes as a resource for spinal cord lesion repair and plasticity. Intl. Symp. on Neural Regeneration, Dec. 2009

Pollak J., Debsi B., Mamer L., Doyle K., Jones B., Shamloo M., Buckwalter M. Functional characterization of the hypoxic-ischemic mouse model of stroke. Society for Neuroscience, October 2009

Pollak J., Debsi B., Mamer L., Lui S., Doyle K., Jones B., Shamloo M., Buckwalter M.  A mouse model for studying functional recovery from stroke. International Stroke Conference, February 2009

McGill J.K., Pollak J., Beal F.M., Browne S.E. Transcriptional abnormalities and mitochondrial function in Huntington’s disease mice. Society for Neuroscience, November 2006

Moussatov S.A., Brown S.E., Pollak J., Mobbs C.V., Kaplitt M.G. Impaired central sensitivity to glucose in an animal model of Huntington’s disease. Society for Neuroscience, November 2006

McGill J.K., Pollak J., Beal F.M., Browne S.E. Impaired thermoregulation and brown fat abnormalities in HD mice. Hereditary Disease Foundation HD Symposium, 2006